"""add oauth server tables

Revision ID: 5edda438d674
Revises: c4e8a1f6b920
Create Date: 2026-09-28 10:56:29.003008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5edda438d674"
down_revision: Union[str, Sequence[str], None] = "c4e8a1f6b920"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=2048), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_uri", sa.String(length=2048), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.create_index("ix_oauth_grant_user_client", ["user_id", "client_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_oauth_grants_user_id"), ["user_id"], unique=False)

    op.create_table(
        "oauth_authorization_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("code_lookup", sa.String(length=64), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_authorization_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_codes_code_lookup"), ["code_lookup"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_codes_grant_id"), ["grant_id"], unique=False
        )

    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.Enum("access", "refresh", name="oauthtokenkind"), nullable=False),
        sa.Column("token_lookup", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_tokens_grant_id"), ["grant_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_oauth_tokens_token_lookup"), ["token_lookup"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_token_lookup"))
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_grant_id"))

    op.drop_table("oauth_tokens")
    with op.batch_alter_table("oauth_authorization_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_codes_grant_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_codes_code_lookup"))

    op.drop_table("oauth_authorization_codes")
    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_grants_user_id"))
        batch_op.drop_index("ix_oauth_grant_user_client")

    op.drop_table("oauth_grants")
    # ### end Alembic commands ###
