"""add token scope and management key

Revision ID: b7f3c9a12d4e
Revises: 29039497405e
Create Date: 2026-08-12 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7f3c9a12d4e"
down_revision: Union[str, Sequence[str], None] = "29039497405e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="write" backfills all existing tokens to write-only.
    with op.batch_alter_table("client_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scope",
                sa.Enum("write", "read", "delete", "full", name="tokenscope"),
                nullable=False,
                server_default="write",
            )
        )

    op.create_table(
        "management_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("management_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_management_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_management_keys_user_id"), ["user_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("management_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_management_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_management_keys_key_hash"))

    op.drop_table("management_keys")

    with op.batch_alter_table("client_tokens", schema=None) as batch_op:
        batch_op.drop_column("scope")

    # ### end Alembic commands ###
