"""add token lookup hash for O(1) auth

Revision ID: c4e8a1f6b920
Revises: b7f3c9a12d4e
Create Date: 2026-08-12 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4e8a1f6b920"
down_revision: Union[str, Sequence[str], None] = "b7f3c9a12d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable: existing rows have no lookup hash and are backfilled lazily on first
    # authenticated use (see auth._match_legacy_token). SQLite treats NULLs as distinct
    # under UNIQUE, so multiple un-backfilled rows coexist.
    with op.batch_alter_table("client_tokens", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token_lookup", sa.String(length=64), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_client_tokens_token_lookup"), ["token_lookup"], unique=True
        )

    with op.batch_alter_table("management_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("key_lookup", sa.String(length=64), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_management_keys_key_lookup"), ["key_lookup"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("management_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_management_keys_key_lookup"))
        batch_op.drop_column("key_lookup")

    with op.batch_alter_table("client_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_tokens_token_lookup"))
        batch_op.drop_column("token_lookup")

    # ### end Alembic commands ###
