"""add oauth dynamic client registration

Revision ID: feaf615e1b1f
Revises: 5edda438d674
Create Date: 2026-09-28 12:18:36.341369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "feaf615e1b1f"
down_revision: Union[str, Sequence[str], None] = "5edda438d674"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_uri", sa.String(length=2048), nullable=True),
        sa.Column("redirect_uris", sqlite.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_clients")
    # ### end Alembic commands ###
